### ISSUE TITLE
Can't play over Firefox

### ISSUE THREAD

**Issue by ravi0lii** [Cardsity/issue-tracker#2]
**Describe the bug**
The game server can't be reached while playing using Firefox because of a TLS error.
![image](https://user-images.githubusercontent.com/31647414/86394983-c1795e00-bc9f-11ea-9cf2-d24e43ce1b6e.png)
The game server has the following log:
```
[INFO] (on_tls_init:405) 02-07-20 18:05:25: TLS Init called!
[2020-07-02 18:05:28] [error] handle_transport_init received error: TLS handshake failed
[2020-07-02 18:05:28] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init)
[INFO] (on_tls_init:405) 02-07-20 18:05:25: TLS Init called!
[2020-07-02 18:05:30] [error] handle_transport_init received error: TLS handshake failed
[2020-07-02 18:05:30] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init)
```

**To Reproduce**
1. Use Firefox
2. Open https://cardsity.app
3. See the error for yourself

**Expected behavior**
You should be able to play normally using Firefox.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 78.0

**Additional context**
It seems that the problem here is the game server.
Additionally, the problem only occurs sometimes (for me on every request)

**Comment by Curve** [comment]
Not sure if it's a game server problem, I will investigate the issue

**Comment by Curve** [comment]
Issue is related to Firefox Version 78.0.1, connecting still works on older firefox versions. Im not sure if I can fix this or if this issue is even related to the game server itself.

Closing this as of now

**Comment by Curve** [comment]
If anyone has suggestions feel free to lead me into the right direction, maybe this issue is related to websocketpp

**Comment by Curve** [comment]
I may have found a fix for the issue I will test tomorrow

**Comment by Curve** [comment]
Fixed in https://github.com/Cardsity/game-server/commit/54cc3ac94572a1c52389420878a19285852ee5cc
